### ISSUE TITLE
class names of Assignment2 are not valid

### ISSUE THREAD

**Issue by yaojialyu** [Yafei18/2020fall-info5100#3]
Hi, I found `Assignment2-1` and `Assignment2-2` are not valid identifiers. Maybe you should rename them.
I think it would be better to avoid such problems and give students a good example. 
Thank you.

**Comment by Yafei18** [comment]
> Hi, I found `Assignment2-1` and `Assignment2-2` are not valid identifiers. Maybe you should rename them.
> I think it would be better to avoid such problems and give students a good example.
> Thank you.

Hey! Assignment2-1 and Assignment2-2 are just used to differentiate between two files. You can name them CalculateEmployeeSalary or SumNumber or whatever you want.
